# Run tests.

name: Run tests

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Packages'
        type: string


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run `tox`
        run: |
          sudo apt update
          sudo apt install tox yapf3 ${{ inputs.packages }}
          tox
